### ISSUE TITLE
Where do the 7z files come from?

### ISSUE THREAD

**Issue by jaytaylor** [Findus23/se-simulator#1]
Howdy,

In the README, it says:

> download the .7z files for the sites you want to generate (I'd recommend to use a file <100MB)

Where are these supposed to come from?

**Comment by Findus23** [comment]
Ah, forgot the most important part:
The source text comes from the stackoverflow database dumps:
https://archive.org/details/stackexchange

**Comment by jaytaylor** [comment]
Fabulous, thanks!
