### ISSUE TITLE
Error: not found: ../../milligram/src/milligram

### ISSUE THREAD

**Issue by jaytaylor** [Findus23/se-simulator#3]
After getting everything built and running, the website produces this error:

    Error: File to import not found or unreadable: ../../milligram/src/milligram.
        on line 15 of web/static/sass/style.scss
    >> @import "../../milligram/src/milligram";
          ^

Is there a step I've missed? :)

<img width="1242" alt="screen shot 2018-04-30 at 2 43 07 pm" src="https://user-images.githubusercontent.com/435652/39451870-07ea9256-4c85-11e8-9ebf-c9666daf0c99.png">

**Comment by Findus23** [comment]
Yes, indeed I still forgot something. 
I included my regular css template as a submodule so you need to run
git submodule init
and/or
git submodule update

**Comment by jaytaylor** [comment]
Woohoo that worked!!!

I've added the instructions to the PR I opened :>

**Comment by Findus23** [comment]
Many thanks. 
I don’t have much time at the moment, but I’ll definitely look into it soon.

**Comment by jaytaylor** [comment]
No hurry, it'll still there ;)
